# Generated by Django 4.2.3 on 2023-08-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='member',
            new_name='members',
        ),
    ]
